# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [
	"nvme"
	"xhci_pci"
	"ahci"
	"usb_storage"
	"usbhid"
	"sd_mod"
	"sr_mod"
  ];
  boot.kernelParams = [ "amd_iommu=on" "vfio-pci.ids=1002:67df,1002:aaf0" "libata.force=4.00:disable"];
  boot.initrd.kernelModules = [ "vfio_virqfd" "vfio_pci" "vfio_iommu_type1" "vfio" ];
  boot.kernelModules = [ "kvm-amd" "vfio_virqfd" "vfio_pci" "vfio_iommu_type1" "vfio" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "zroot/ROOT/default";
      fsType = "zfs";
    };

  fileSystems."/etc/ssh" =
    { device = "zroot/data/ssh";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "zroot/data/home";
      fsType = "zfs";
    };

  fileSystems."/usr/local" =
    { device = "zroot/data/usr-local";
      fsType = "zfs";
    };

  fileSystems."/etc/NetworkManager/system-connections" =
    { device = "zroot/data/connections";
      fsType = "zfs";
    };

  fileSystems."/home/maxhero/Games" =
    { device = "zroot/games/home";
      fsType = "zfs";
    };

  fileSystems."/home/maxhero/.cache/btdownloads" =
    { device = "zroot/data/btdownloads";
      fsType = "zfs";
    };

  fileSystems."/home/maxhero/.local/share/Steam/steamapps/common" =
    { device = "zroot/games/steam";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5E85-DE1E";
      fsType = "vfat";
    };

  fileSystems."/data/puppet" =
    { device = "/dev/disk/by-uuid/f810ae2c-7956-4300-93a4-1894b50501f7";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/66fee4ef-15f3-434b-b567-54f7e0ca0ef3"; }
    ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
