# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "cryptd"
    "sd_mod"
    "sr_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "zroot/ROOT/default";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "zroot/data/home";
    fsType = "zfs";
  };

  fileSystems."/home/maxhero/projects" = {
    device = "zroot/data/maxhero-projects";
    fsType = "zfs";
  };

  fileSystems."/etc/ssh" = {
    device = "zroot/data/maxhero-projects";
    fsType = "zfs";
  };

  fileSystems."/etc/NetworkManager/system-connections" = {
    device = "zroot/data/connections";
    fsType = "zfs";
  };

  fileSystems."/usr/local" = {
    device = "zroot/data/usr-local";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/nvme1n1p1";
    fsType = "vfat";
  };

  swapDevices = [{ device = "/dev/nvme0n1p2"; }];

  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
