# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" "cryptd" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];


  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1de09e23-882e-43c0-8fa9-f8965d907d99";
    fsType = "ext4";
  }

  boot.initrd.luks.devices."nixos-root".device = "/dev/disk/by-uuid/41eef534-4c0e-4974-b893-cce12355a1b1"

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E760-D951";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  /*
  boot.initrd.luks.devices.root = {
    device = "/dev/disk/by-uuid/2afb6cb6-fc98-4103-ab83-3fe6282db083";
    preLVM = true;
    allowDiscards = true;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4fe10a63-89d2-4b0e-ada7-b1af00cfe85f";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/E760-D951";
    fsType = "vfat";
  };
  */

  swapDevices = [ ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
